PRINT 'Merging into [Dim].[CountryCode] .... ';
--SET IDENTITY_INSERT [Dim].[CountryCode] ON;

WITH SRC AS
(
    SELECT * FROM(
        VALUES
        ('TON',     'Tonga',                                9,      61,     -1),
        ('PAN',     'Panama',                               19,     419,    13),
        ('LSO',     'Lesotho',                              2,      202,    18),
        ('MRT',     'Mauritania',                           2,      202,    11),
        ('CZE',     'Czechia',                              150,    151,    -1),
        ('VCT',     'Saint Vincent and the Grenadines',     19,     419,    29),
        ('UKR',     'Ukraine',                              150,    151,    -1),
        ('CHN',     'China',                                142,    30,     -1),
        ('CAN',     'Canada',                               19,     21,     -1),
        ('LAO',     'Laos',                                 142,    35,     -1),
        ('ITA',     'Italy',                                150,    39,     -1),
        ('AUS',     'Australia',                            9,      53,     -1),
        ('CUB',     'Cuba',                                 19,     419,    29),
        ('FIN',     'Finland',                              150,    154,    -1),
        ('SVN',     'Slovenia',                             150,    39,     -1),
        ('TZA',     'Tanzania',                             2,      202,    14),
        ('VUT',     'Vanuatu',                              9,      54,     -1),
        ('EGY',     'Egypt',                                2,      15,     -1),
        ('BLR',     'Belarus',                              150,    151,    -1),
        ('JOR',     'Jordan',                               142,    145,    -1),
        ('LIE',     'Liechtenstein',                        150,    155,    -1),
        ('NOR',     'Norway',                               150,    154,    -1),
        ('DMA',     'Dominica',                             19,     419,    29),
        ('FRA',     'France',                               150,    155,    -1),
        ('STP',     'Sao Tome and Principe',                2,      202,    17),
        ('PRT',     'Portugal',                             150,    39,     -1),
        ('YEM',     'Yemen',                                142,    145,    -1),
        ('ARG',     'Argentina',                            19,     419,    5),
        ('GRD',     'Grenada',                              19,     419,    29),
        ('IDN',     'Indonesia',                            142,    35,     -1),
        ('MEX',     'Mexico',                               19,     419,    13),
        ('SYR',     'Syria',                                142,    145,    -1),
        ('BWA',     'Botswana',                             2,      202,    18),
        ('ETH',     'Ethiopia',                             2,      202,    14),
        ('CRI',     'Costa Rica',                           19,     419,    13),
        ('LCA',     'Saint Lucia',                          19,     419,    29),
        ('LBN',     'Lebanon',                              142,    145,    -1),
        ('BTN',     'Bhutan',                               142,    34,     -1),
        ('BRB',     'Barbados',                             19,     419,    29),
        ('KNA',     'Saint Kitts and Nevis',                19,     419,    29),
        ('NLD',     'Netherlands',                          150,    155,    -1),
        ('AZE',     'Azerbaijan',                           142,    145,    -1),
        ('MNG',     'Mongolia',                             142,    30,     -1),
        ('SUR',     'Suriname',                             19,     419,     5),
        ('MYS',     'Malaysia',                             142,    35,     -1),
        ('PSE',     'West Bank and Gaza',                   142,    145,    -1),
        ('BOL',     'Bolivia',                              19,     419,    5),
        ('MDV',     'Maldives',                             142,    34,     -1),
        ('BIH',     'Bosnia and Herzegovina',               150,    39,     -1),
        ('ALB',     'Albania',                              150,    39,     -1),
        ('KIR',     'Kiribati',                             9,      57,     -1),
        ('GHA',     'Ghana',                                2,      202,    11),
        ('GBR',     'United Kingdom',                       150,    154,    -1),
        ('GUY',     'Guyana',                               19,     419,    5),
        ('MKD',     'North Macedonia',                      150,    39,     -1),
        ('ARE',     'United Arab Emirates',                 142,    145,    -1),
        ('SAU',     'Saudi Arabia',                         142,    145,    -1),
        ('ISL',     'Iceland',                              150,    154,    -1),
        ('QAT',     'Qatar',                                142,    145,    -1),
        ('CYP',     'Cyprus',                               142,    145,    -1),
        ('BRN',     'Brunei',                               142,    35,     -1),
        ('DEU',     'Germany',                              150,    155,    -1),
        ('MDG',     'Madagascar',                           2,      202,    14),
        ('ATG',     'Antigua and Barbuda',                  19,     419,    29),
        ('KEN',     'Kenya',                                2,      202,    14),
        ('MOZ',     'Mozambique',                           2,      202,    14),
        ('MHL',     'Marshall Islands',                     9,      57,     -1),
        ('COM',     'Comoros',                              2,      202,    14),
        ('HTI',     'Haiti',                                19,     419,    29),
        ('BHR',     'Bahrain',                              142,    145,    -1),
        ('USA',     'US',                                   19,     21,     -1),
        ('AUT',     'Austria',                              150,    155,    -1),
        ('GNB',     'Guinea-Bissau',                        2,      202,    11),
        ('MCO',     'Monaco',                               150,    155,    -1),
        ('FJI',     'Fiji',                                 9,      54,     -1),
        ('TWN',     'Taiwan',                               142,    30,     -1),
        ('COD',     'Congo (Kinshasa)',                     2,      202,    17),
        ('DJI',     'Djibouti',                             2,      202,    14),
        ('RWA',     'Rwanda',                               2,      202,    14),
        ('PRY',     'Paraguay',                             19,     419,    5),
        ('CIV',     'Cote d''Ivoire',                       2,      202,    1),
        ('SWE',     'Sweden',                               150,    154,    -1),
        ('SYC',     'Seychelles',                           2,      202,    14),
        ('NAM',     'Namibia',                              2,      202,    18),
        ('SWZ',     'Eswatini',                             2,      202,    18),
        ('AGO',     'Angola',                               2,      202,    17),
        ('POL',     'Poland',                               150,    151,    -1),
        ('MUS',     'Mauritius',                            2,      202,    14),
        ('SLB',     'Solomon Islands',                      9,      54,     -1),
        ('SEN',     'Senegal',                              2,      202,    11),
        ('LKA',     'Sri Lanka',                            142,    34,     -1),
        ('DOM',     'Dominican Republic',                   19,     419,    29),
        ('AND',     'Andorra',                              150,    39,     -1),
        ('TLS',     'Timor-Leste',                          142,    35,     -1),
        ('GTM',     'Guatemala',                            19,     419,    13),
        ('AFG',     'Afghanistan',                          142,    34,     -1),
        ('ZAF',     'South Africa',                         2,      202,    18),
        ('THA',     'Thailand',                             142,    35,     -1),
        ('KHM',     'Cambodia',                             142,    35,     -1),
        ('GMB',     'Gambia',                               2,      202,    11),
        ('TUR',     'Turkey',                               142,    145,    -1),
        ('GEO',     'Georgia',                              142,    145,    -1),
        ('MNE',     'Montenegro',                           150,    39,     -1),
        ('UGA',     'Uganda',                               2,      202,    14),
        ('BHS',     'Bahamas',                              19,     419,    29),
        ('RKS',     'Kosovo',                               150,    39,     -1),
        ('HRV',     'Croatia',                              150,    39,     -1),
        ('BFA',     'Burkina Faso',                         2,      202,    11),
        ('LTU',     'Lithuania',                            150,    154,    -1),
        ('GRC',     'Greece',                               150,    39,     -1),
        ('LBR',     'Liberia',                              2,      202,    11),
        ('UZB',     'Uzbekistan',                           142,    143,    -1),
        ('ECU',     'Ecuador',                              19,     419,    5),
        ('NPL',     'Nepal',                                142,    34,     -1),
        ('PLW',     'Palau',                                9,      57,     -1),
        ('JPN',     'Japan',                                142,    30,     -1),
        ('BGD',     'Bangladesh',                           142,    34,     -1),
        ('ARM',     'Armenia',                              142,    145,    -1),
        ('FSM',     'Micronesia',                           -1,     -1,   -1),
        ('PNG',     'Papua New Guinea',                     9,      54,     -1),
        ('BRA',     'Brazil',                               19,     419,    5),
        ('ESP',     'Spain',                                150,    39,     -1),
        ('MLI',     'Mali',                                 2,      202,    11),
        ('COL',     'Colombia',                             19,     419,    5),
        ('CAF',     'Central African Republic',             2,      202,    17),
        ('SLV',     'El Salvador',                          19,     419,    13),
        ('BGR',     'Bulgaria',                             150,    151,    -1),
        ('ZMB',     'Zambia',                               2,      202,    14),
        ('KWT',     'Kuwait',                               142,    145,    -1),
        ('HUN',     'Hungary',                              150,    151,    -1),
        ('CHL',     'Chile',                                19,     419,    5),
        ('NIC',     'Nicaragua',                            19,     419,    13),
        ('MDA',     'Moldova',                              150,    151,    -1),
        ('VEN',     'Venezuela',                            19,     419,    5),
        ('CPV',     'Cabo Verde',                           2,      202,    11),
        ('VNM',     'Vietnam',                              142,    35,     -1),
        ('CMR',     'Cameroon',                             2,      202,    17),
        ('SDN',     'Sudan',                                2,      15,     -1),
        ('BLZ',     'Belize',                               19,     419,    13),
        ('MMR',     'Burma',                                142,    35,     -1),
        ('NGA',     'Nigeria',                              2,      202,    11),
        ('BDI',     'Burundi',                              2,      202,    14),
        ('KGZ',     'Kyrgyzstan',                           142,    143,    -1),
        ('GIN',     'Guinea',                               2,      202,    11),
        ('IRQ',     'Iraq',                                 142,    145,    -1),
        ('ZWE',     'Zimbabwe',                             2,      202,    14),
        ('SSD',     'South Sudan',                          2,      202,    14),
        ('GAB',     'Gabon',                                2,      202,    17),
        ('TCD',     'Chad',                                 2,      202,    17),
        ('KOR',     'Korea South',                          142,    30,     -1),
        ('JAM',     'Jamaica',                              19,     419,    29),
        ('PAK',     'Pakistan',                             142,    34,     -1),
        ('VAT',     'Holy See',                             150,    39,     -1),
        ('URY',     'Uruguay',                              19,     419,    5 ),
        ('ERI',     'Eritrea',                              2,      202,    14),
        ('KAZ',     'Kazakhstan',                           142,    143,    -1),
        ('DZA',     'Algeria',                              2,      15,     -1),
        ('SRB',     'Serbia',                               150,    39,     -1),
        ('LUX',     'Luxembourg',                           150,    155,    -1),
        ('IRN',     'Iran',                                 142,    34,     -1),
        ('SGP',     'Singapore',                            142,    35,     -1),
        ('NZL',     'New Zealand',                          9,      53,     -1),
        ('SLE',     'Sierra Leone',                         2,      202,    11),
        ('BEL',     'Belgium',                              150,    155,    -1),
        ('IND',     'India',                                142,    34,     -1),
        ('TTO',     'Trinidad and Tobago',                  19,     419,    29),
        ('MLT',     'Malta',                                150,    39,     -1),
        ('PHL',     'Philippines',                          142,    35,     -1),
        ('TGO',     'Togo',                                 2,      202,    11),
        ('EST',     'Estonia',                              150,    154,    -1),
        ('GNQ',     'Equatorial Guinea',                    2,      202,    17),
        ('SMR',     'San Marino',                           150,    39,     -1),
        ('ROU',     'Romania',                              150,    151,    -1),
        ('MWI',     'Malawi',                               2,      202,    14),
        ('TUN',     'Tunisia',                              2,      15,     -1),
        ('IRL',     'Ireland',                              150,    154,    -1),
        ('COG',     'Congo (Brazzaville)',                  2,      202,    17),
        ('PER',     'Peru',                                 19,     419,    5),
        ('LVA',     'Latvia',                               150,    154,    -1),
        ('BEN',     'Benin',                                2,      202,    11),
        ('SOM',     'Somalia',                              2,      202,    14),
        ('CHE',     'Switzerland',                          150,    155,    -1),
        ('ISR',     'Israel',                               142,    145,    -1),
        ('NER',     'Niger',                                2,      202,    11),
        ('LBY',     'Libya',                                2,      15,     -1),
        ('TJK',     'Tajikistan',                           142,    143,    -1),
        ('SVK',     'Slovakia',                             150,    151,    -1),
        ('WSM',     'Samoa',                                9,      61,     -1),
        ('RUS',     'Russia',                               150,    151,    -1),
        ('HND',     'Honduras',                             19,     419,    13),
        ('MAR',     'Morocco',                              2,      15,     -1),
        ('DNK',     'Denmark',                              150,    154,    -1),
        ('OMN',     'Oman',                                 142,    145,    -1)
      
    ) AS Countries
    (     
        [CountryCode], 
        [Country/Region],
        [RegionCode],
        [SubRegionCode],
        [IntermediateRegionCode]
    )
)

MERGE INTO [Dim].[CountryCode] AS TGT
USING SRC
    ON TGT.[CountryCode] = SRC.[CountryCode]

WHEN MATCHED THEN
    UPDATE
    SET
        [CountryCode]               = SRC.[CountryCode],
        [Country/Region]            = SRC.[Country/Region],
        [RegionCode]                = SRC.[RegionCode],
        [SubRegionCode]             = SRC.[SubRegionCode],
        [IntermediateRegionCode]    = SRC.[IntermediateRegionCode]

WHEN NOT MATCHED BY TARGET THEN
    INSERT 
        (
            [CountryCode],
            [Country/Region],
            [RegionCode],
            [SubRegionCode],
            [IntermediateRegionCode]
        )
    VALUES 
        (
            SRC.[CountryCode],
            SRC.[Country/Region],
            SRC.[RegionCode],
            SRC.[SubRegionCode],
            SRC.[IntermediateRegionCode]
        )

WHEN NOT MATCHED BY SOURCE THEN
    DELETE;


--SET IDENTITY_INSERT [Dim].[CountryCode] OFF;