PRINT 'Merging into [Dim].[Countries] .... ';
SET IDENTITY_INSERT [Dim].[Countries] ON;

WITH SRC AS
(
    SELECT * FROM(
        VALUES
        (1,      'TON',     'Tonga',                                9,      61,     -1),
        (2,      'PAN',     'Panama',                               19,     419,    13),
        (3,      'LSO',     'Lesotho',                              2,      202,    18),
        (4,      'MRT',     'Mauritania',                           2,      202,    11),
        (5,      'CZE',     'Czechia',                              150,    151,    -1),
        (6,      'VCT',     'Saint Vincent and the Grenadines',     19,     419,    29),
        (7,      'UKR',     'Ukraine',                              150,    151,    -1),
        (8,      'CHN',     'China',                                142,    30,     -1),
        (9,      'CAN',     'Canada',                               19,     21,     -1),
        (10,     'LAO',     'Laos',                                 142,    35,     -1),
        (11,     'ITA',     'Italy',                                150,    39,     -1),
        (12,     'AUS',     'Australia',                            9,      53,     -1),
        (13,     'CUB',     'Cuba',                                 19,     419,    29),
        (14,     'FIN',     'Finland',                              150,    154,    -1),
        (15,     'SVN',     'Slovenia',                             150,    39,     -1),
        (16,     'TZA',     'Tanzania',                             2,      202,    14),
        (17,     'VUT',     'Vanuatu',                              9,      54,     -1),
        (18,     'EGY',     'Egypt',                                2,      15,     -1),
        (19,     'BLR',     'Belarus',                              150,    151,    -1),
        (20,     'JOR',     'Jordan',                               142,    145,    -1),
        (21,     'LIE',     'Liechtenstein',                        150,    155,    -1),
        (22,     'NOR',     'Norway',                               150,    154,    -1),
        (23,     'DMA',     'Dominica',                             19,     419,    29),
        (24,     'FRA',     'France',                               150,    155,    -1),
        (25,     'STP',     'Sao Tome and Principe',                2,      202,    17),
        (26,     'PRT',     'Portugal',                             150,    39,     -1),
        (27,     'YEM',     'Yemen',                                142,    145,    -1),
        (28,     'ARG',     'Argentina',                            19,     419,    5),
        (29,     'GRD',     'Grenada',                              19,     419,    29),
        (30,     'IDN',     'Indonesia',                            142,    35,     -1),
        (31,     'MEX',     'Mexico',                               19,     419,    13),
        (32,     'SYR',     'Syria',                                142,    145,    -1),
        (33,     'BWA',     'Botswana',                             2,      202,    18),
        (34,     'ETH',     'Ethiopia',                             2,      202,    14),
        (35,     'CRI',     'Costa Rica',                           19,     419,    13),
        (36,     'LCA',     'Saint Lucia',                          19,     419,    29),
        (37,     'LBN',     'Lebanon',                              142,    145,    -1),
        (38,     'BTN',     'Bhutan',                               142,    34,     -1),
        (39,     'BRB',     'Barbados',                             19,     419,    29),
        (40,     'KNA',     'Saint Kitts and Nevis',                19,     419,    29),
        (41,     'NLD',     'Netherlands',                          150,    155,    -1),
        (42,     'AZE',     'Azerbaijan',                           142,    145,    -1),
        (43,     'MNG',     'Mongolia',                             142,    30,     -1),
        (44,     'SUR',     'Suriname',                             19,     419,     5),
        (45,     'MYS',     'Malaysia',                             142,    35,     -1),
        (46,     'PSE',     'West Bank and Gaza',                   142,    145,    -1),
        (47,     'BOL',     'Bolivia',                              19,     419,    5),
        (48,     'MDV',     'Maldives',                             142,    34,     -1),
        (49,     'BIH',     'Bosnia and Herzegovina',               150,    39,     -1),
        (50,     'ALB',     'Albania',                              150,    39,     -1),
        (51,     'KIR',     'Kiribati',                             9,      57,     -1),
        (52,     'GHA',     'Ghana',                                2,      202,    11),
        (53,     'GBR',     'United Kingdom',                       150,    154,    -1),
        (54,     'GUY',     'Guyana',                               19,     419,    5),
        (55,     'MKD',     'North Macedonia',                      150,    39,     -1),
        (56,     'ARE',     'United Arab Emirates',                 142,    145,    -1),
        (57,     'SAU',     'Saudi Arabia',                         142,    145,    -1),
        (58,     'ISL',     'Iceland',                              150,    154,    -1),
        (59,     'QAT',     'Qatar',                                142,    145,    -1),
        (60,     'CYP',     'Cyprus',                               142,    145,    -1),
        (61,     'BRN',     'Brunei',                               142,    35,     -1),
        (62,     'DEU',     'Germany',                              150,    155,    -1),
        (63,     'MDG',     'Madagascar',                           2,      202,    14),
        (64,     'ATG',     'Antigua and Barbuda',                  19,     419,    29),
        (65,     'KEN',     'Kenya',                                2,      202,    14),
        (66,     'MOZ',     'Mozambique',                           2,      202,    14),
        (67,     'MHL',     'Marshall Islands',                     9,      57,     -1),
        (68,     'COM',     'Comoros',                              2,      202,    14),
        (69,     'HTI',     'Haiti',                                19,     419,    29),
        (70,     'BHR',     'Bahrain',                              142,    145,    -1),
        (71,     'USA',     'US',                                   19,     21,     -1),
        (72,     'AUT',     'Austria',                              150,    155,    -1),
        (73,     'GNB',     'Guinea-Bissau',                        2,      202,    11),
        (74,     'MCO',     'Monaco',                               150,    155,    -1),
        (75,     'FJI',     'Fiji',                                 9,      54,     -1),
        (76,     'TWN',     'Taiwan',                               142,    30,     -1),
        (77,     'COD',     'Congo (Kinshasa)',                     2,      202,    17),
        (78,     'DJI',     'Djibouti',                             2,      202,    14),
        (79,     'RWA',     'Rwanda',                               2,      202,    14),
        (80,     'PRY',     'Paraguay',                             19,     419,    5),
        (81,     'CIV',     'Cote d''Ivoire',                       2,      202,    1),
        (82,     'SWE',     'Sweden',                               150,    154,    -1),
        (83,     'SYC',     'Seychelles',                           2,      202,    14),
        (84,     'NAM',     'Namibia',                              2,      202,    18),
        (85,     'SWZ',     'Eswatini',                             2,      202,    18),
        (86,     'AGO',     'Angola',                               2,      202,    17),
        (87,     'POL',     'Poland',                               150,    151,    -1),
        (88,     'MUS',     'Mauritius',                            2,      202,    14),
        (89,     'SLB',     'Solomon Islands',                      9,      54,     -1),
        (90,     'SEN',     'Senegal',                              2,      202,    11),
        (91,     'LKA',     'Sri Lanka',                            142,    34,     -1),
        (92,     'DOM',     'Dominican Republic',                   19,     419,    29),
        (93,     'AND',     'Andorra',                              150,    39,     -1),
        (94,     'TLS',     'Timor-Leste',                          142,    35,     -1),
        (95,     'GTM',     'Guatemala',                            19,     419,    13),
        (96,     'AFG',     'Afghanistan',                          142,    34,     -1),
        (97,     'ZAF',     'South Africa',                         2,      202,    18),
        (98,     'THA',     'Thailand',                             142,    35,     -1),
        (99,     'KHM',     'Cambodia',                             142,    35,     -1),
        (100,    'GMB',     'Gambia',                               2,      202,    11),
        (101,    'TUR',     'Turkey',                               142,    145,    -1),
        (102,    'GEO',     'Georgia',                              142,    145,    -1),
        (103,    'MNE',     'Montenegro',                           150,    39,     -1),
        (104,    'UGA',     'Uganda',                               2,      202,    14),
        (105,    'BHS',     'Bahamas',                              19,     419,    29),
        (106,    'RKS',     'Kosovo',                               150,    39,     -1),
        (107,    'HRV',     'Croatia',                              150,    39,     -1),
        (108,    'BFA',     'Burkina Faso',                         2,      202,    11),
        (109,    'LTU',     'Lithuania',                            150,    154,    -1),
        (110,    'GRC',     'Greece',                               150,    39,     -1),
        (110,    'LBR',     'Liberia',                              2,      202,    11),
        (111,    'UZB',     'Uzbekistan',                           142,    143,    -1),
        (112,    'ECU',     'Ecuador',                              19,     419,    5),
        (113,    'NPL',     'Nepal',                                142,    34,     -1),
        (114,    'PLW',     'Palau',                                9,      57,     -1),
        (115,    'JPN',     'Japan',                                142,    30,     -1),
        (116,    'BGD',     'Bangladesh',                           142,    34,     -1),
        (117,    'ARM',     'Armenia',                              142,    145,    -1),
        (118,    'FSM',     'Micronesia',                           NULL,   NULL,   -1),
        (119,    'PNG',     'Papua New Guinea',                     9,      54,     -1),
        (120,    'BRA',     'Brazil',                               19,     419,    5),
        (121,    'ESP',     'Spain',                                150,    39,     -1),
        (122,    'MLI',     'Mali',                                 2,      202,    11),
        (123,    'COL',     'Colombia',                             19,     419,    5),
        (124,    'CAF',     'Central African Republic',             2,      202,    17),
        (125,    'SLV',     'El Salvador',                          19,     419,    13),
        (126,    'BGR',     'Bulgaria',                             150,    151,    -1),
        (127,    'ZMB',     'Zambia',                               2,      202,    14),
        (128,    'KWT',     'Kuwait',                               142,    145,    -1),
        (129,    'HUN',     'Hungary',                              150,    151,    -1),
        (130,    'CHL',     'Chile',                                19,     419,    5),
        (131,    'NIC',     'Nicaragua',                            19,     419,    13),
        (132,    'MDA',     'Moldova',                              150,    151,    -1),
        (133,    'VEN',     'Venezuela',                            19,     419,    5),
        (134,    'CPV',     'Cabo Verde',                           2,      202,    11),
        (135,    'VNM',     'Vietnam',                              142,    35,     -1),
        (136,    'CMR',     'Cameroon',                             2,      202,    17),
        (137,    'SDN',     'Sudan',                                2,      15,     -1),
        (138,    'BLZ',     'Belize',                               19,     419,    13),
        (139,    'MMR',     'Burma',                                142,    35,     -1),
        (140,    'NGA',     'Nigeria',                              2,      202,    11),
        (141,    'BDI',     'Burundi',                              2,      202,    14),
        (142,    'KGZ',     'Kyrgyzstan',                           142,    143,    -1),
        (143,    'GIN',     'Guinea',                               2,      202,    11),
        (144,    'IRQ',     'Iraq',                                 142,    145,    -1),
        (145,    'ZWE',     'Zimbabwe',                             2,      202,    14),
        (146,    'SSD',     'South Sudan',                          2,      202,    14),
        (147,    'GAB',     'Gabon',                                2,      202,    17),
        (148,    'TCD',     'Chad',                                 2,      202,    17),
        (149,    'KOR',     'Korea South',                          142,    30,     -1),
        (150,    'JAM',     'Jamaica',                              19,     419,    29),
        (151,    'PAK',     'Pakistan',                             142,    34,     -1),
        (152,    'VAT',     'Holy See',                             150,    39,     -1),
        (153,    'URY',     'Uruguay',                              19,     419,    5 ),
        (154,    'ERI',     'Eritrea',                              2,      202,    14),
        (155,    'KAZ',     'Kazakhstan',                           142,    143,    -1),
        (156,    'DZA',     'Algeria',                              2,      15,     -1),
        (157,    'SRB',     'Serbia',                               150,    39,     -1),
        (158,    'LUX',     'Luxembourg',                           150,    155,    -1),
        (159,    'IRN',     'Iran',                                 142,    34,     -1),
        (160,    'SGP',     'Singapore',                            142,    35,     -1),
        (161,    'NZL',     'New Zealand',                          9,      53,     -1),
        (162,    'SLE',     'Sierra Leone',                         2,      202,    11),
        (163,    'BEL',     'Belgium',                              150,    155,    -1),
        (164,    'IND',     'India',                                142,    34,     -1),
        (165,    'TTO',     'Trinidad and Tobago',                  19,     419,    29),
        (166,    'MLT',     'Malta',                                150,    39,     -1),
        (167,    'PHL',     'Philippines',                          142,    35,     -1),
        (168,    'TGO',     'Togo',                                 2,      202,    11),
        (169,    'EST',     'Estonia',                              150,    154,    -1),
        (170,    'GNQ',     'Equatorial Guinea',                    2,      202,    17),
        (171,    'SMR',     'San Marino',                           150,    39,     -1),
        (172,    'ROU',     'Romania',                              150,    151,    -1),
        (173,    'MWI',     'Malawi',                               2,      202,    14),
        (174,    'TUN',     'Tunisia',                              2,      15,     -1),
        (175,    'IRL',     'Ireland',                              150,    154,    -1),
        (176,    'COG',     'Congo (Brazzaville)',                  2,      202,    17),
        (177,    'PER',     'Peru',                                 19,     419,    5),
        (178,    'LVA',     'Latvia',                               150,    154,    -1),
        (179,    'BEN',     'Benin',                                2,      202,    11),
        (180,    'SOM',     'Somalia',                              2,      202,    14),
        (181,    'CHE',     'Switzerland',                          150,    155,    -1),
        (182,    'ISR',     'Israel',                               142,    145,    -1),
        (183,    'NER',     'Niger',                                2,      202,    11),
        (184,    'LBY',     'Libya',                                2,      15,     -1),
        (185,    'TJK',     'Tajikistan',                           142,    143,    -1),
        (186,    'SVK',     'Slovakia',                             150,    151,    -1),
        (187,    'WSM',     'Samoa',                                9,      61,     -1),
        (188,    'RUS',     'Russia',                               150,    151,    -1),
        (189,    'HND',     'Honduras',                             19,     419,    13),
        (190,    'MAR',     'Morocco',                              2,      15,     -1),
        (191,    'DNK',     'Denmark',                              150,    154,    -1),
        (192,    'OMN',     'Oman',                                 142,    145,    -1)
      
    ) AS Countries
    (     
        [CountryId],
        [CountryCode], 
        [Country/Region],
        [RegionCode],
        [SubRegionCode],
        [IntermediateRegionCode]
    )
)

MERGE INTO [Dim].[Countries] AS TGT
USING SRC
    ON TGT.[CountryId] = SRC.[CountryId]

WHEN MATCHED THEN
    UPDATE
    SET
        [CountryId]                 = SRC.[CountryId],
        [CountryCode]               = SRC.[CountryCode],
        [Country/Region]            = SRC.[Country/Region],
        [RegionCode]                = SRC.[RegionCode],
        [SubRegionCode]             = SRC.[SubRegionCode],
        [IntermediateRegionCode]    = SRC.[IntermediateRegionCode]

WHEN NOT MATCHED BY TARGET THEN
    INSERT 
        (
            [CountryId],
            [CountryCode],
            [Country/Region],
            [RegionCode],
            [SubRegionCode],
            [IntermediateRegionCode]
        )
    VALUES 
        (
            SRC.[CountryId],
            SRC.[CountryCode],
            SRC.[Country/Region],
            SRC.[RegionCode],
            SRC.[SubRegionCode],
            SRC.[IntermediateRegionCode]
        )

WHEN NOT MATCHED BY SOURCE THEN
    DELETE;


SET IDENTITY_INSERT [Dim].[Countries] OFF;